### ISSUE TITLE
Cheat guard 'Time required between identical actions' only enforced during same session

### ISSUE THREAD

**Issue by slai1** [FMCorz/moodle-block_xp#115]
With 'Time required between identical actions' set to any high number, it should prevent users from spamming points.
However, if the user logs out and back in, it resets the clock and they can continue to earn XP within the restricted time window.

**Comment by FMCorz** [comment]
Thank you for the report @slai1. This is an intentional limitation of the _cheat guard_, and we are aware of the methods a student can go about to circumvent its mechanisms. If you need a more robust cheat guard, please consider [Level up! Plus](https://levelup.plus).

See also: [Cheat guard documentation](https://levelup.plus/docs/article/level-up-cheat-guard)
