### ISSUE TITLE
errors in rule creation

### ISSUE THREAD

**Issue by frankfenix** [FMCorz/moodle-block_xp#118]
errors in rule creation:
When entering the plugin configuration, rules section, it begins to create and create nonsense rules, and it does not always allow deleting them, since it does not always show the button to delete them. Create many rules automatically.

I would also like to know how to create rules that are NOT based on system events, since a student gets experience points too easy and fast this way. Just keep in mind the rules you create and nothing else.

please help

![image](https://user-images.githubusercontent.com/33874898/110873075-f746fb80-829e-11eb-9485-a31b64d0051a.png)

**Comment by FMCorz** [comment]
The rules that are created by default are based off the rules set in the settings of the plugin (Site admin > Plugins > Blocks > Level up! > Default rules), you may change them as you wish.

To delete the rules, click the Trash icon seen on your screenshots.

All rules will use events, if they occur too frequently you may either use other events, or use the cheat guard. We recommend checking the course logs in order to get a sense of what is too frequent, and what isn't.

Closing this issue as this does not appear to be a bug.
