### ISSUE TITLE
Block disappears on Student's page

### ISSUE THREAD

**Issue by TatyGoRa** [FMCorz/moodle-block_xp#133]
The block works fine at first, but then I add the badges block and for some reason, the students lose visibility of the block. It appears on the teacher's page, but not on students. How can I fix this so students can see it again?

**Comment by FMCorz** [comment]
Hi @TatyGoRa 

Thank you for your report.

Would you please confirm each of the following?

- What version of Moodle are you using?
- What versions of XP and XP+ are you using?
- What theme is being used?
- Is the "Student page" the profile page?
- The exact steps followed from adding the block to seeing it "disappear".

Random though, have you tried switching to the default theme (Boost) to see if the block becomes visible again?

Thank you!

**Comment by FMCorz** [comment]
Hi Taty,

Have you tried adding the badges block first, and then adding Level Up XP and see if that makes any difference?

If might be helpful for us to have a look at your Moodle site to investigate, would you please contact me at (support at levelup dot plus) so that we can work to find a solution?

Thank you!

**Comment by FMCorz** [comment]
Closing for now, please let us know if the issue persists.
