### ISSUE TITLE
Enable negative points

### ISSUE THREAD

**Issue by Canx** [FMCorz/moodle-block_xp#73]
I would like to have negative points for some events, for example, when a student triggers the "exceed the available attempts for questionary" event.

Currently an [abs](https://github.com/FMCorz/moodle-block_xp/blob/7d3b57fd6e1dc07a59490b64abba61c020d14dea/classes/filter.php#L192) function is applied that avoids this.

**Comment by FMCorz** [comment]
Thanks for the suggestion.

Initially I added that code there because I strictly wanted to avoid misconfigurations. However, I'm not against allowing negative numbers. There will be a bit of work to do to ensure that the total amount of XP does not fall under zero though.

What event were you referring to exactly? Could expand a bit on what use case you are aiming for? Very few actions in Moodle can be seen as negative, from my perspective. In fact, I would even be surprised if there were any. 

Thanks!
Fred

**Comment by Canx** [comment]
Basically, I was trying to find a way of penalizing students who spends more than one attempt (instead of promoting it) in a questionary. 

Currently I have a rule that add points every time a student submit a questionary, but some of them resubmit more times to gain extra points to achieve a better grade.

Now, having the completion activity feature in the pro version there is less need for this because the questionary is only rewarded one time, when the student passes it.

Other potential case is plagiarism, I haven't checked but ideally I would match a plagiarism detection event and then I would penalize the student. I haven't checked though, if any plagiarism plugin does this.

Again, the completion activity feature would partially solve this, because the task again would not pass.

Not sure now if there are more cases but I guess it's not a superimportant issue.

**Comment by FMCorz** [comment]
Another way to achieve is to leverage the resilient cheat guard in _Plus_ which would totally prevent the student from earning points by submitting the questionnaire again. So long as the duration of the cheat guard is long enough.

**Comment by FMCorz** [comment]
I have put more thoughts into this the negative points, and while I understand that subtracting points from students may be interesting, negative feedback in itself can have quite a bad impact on the engagement of students. Strictly speaking about gamification, I would personally prefer for users to earn less when they under-perform, than _lose_ points when they do. IMHO students having difficulties should be encouraged rather than penalised.

Of course, what is described above are students that _cheat_ to get more points. That should be countered by using the cheat guard, or rewards that cannot be cumulative such as activity completion.  Alternatively, it is always possible for an educator to manually edit the points of a student, and level them down if need be. Plagiarism is another example where manual intervention is advised.

I should add that one issue with subtracting points is the risk of leveling down the student themselves. They could then be congratulated again for reaching back a level they had previously attained. I'm skeptical that this would resonate well with students. In fact, _Level up!_ strictly does not use points as a currency, they are experience points and experience should in general not be taken away from anybody.

I will close this issue on the basis that negative points are not advised. Thank you for your suggestion!
