### ISSUE TITLE
Rule that overrides points with the grade obtained

### ISSUE THREAD

**Issue by Canx** [FMCorz/moodle-block_xp#76]
This rule would contain one rule that has a gradable component associated and would use the grading points obtained as points for the filter.

**Comment by FMCorz** [comment]
Thanks for the suggestion. I think this is somehow related to #25. However, I've identified a few different ways that grade want to be used. (Reward for receiving a grade, a passing grade, reward based on the grade itself).

There are also questions as to how this works when a students receives a grade of 10/20, then pass their assignment again and obtain a 13/20. Realistically it makes sense for a student to get the additional 3, but again, it only adds to the challenge of pulling this off properly.

I've been working on rewarding a student for receiving a grade, but it is much more complicated than it sounds to be implemented in a sensible manner. Under the hood, Moodle triggers the events `user_graded` a lot of the time, and it is difficult to only capture the relevant ones.

Also, such a feature will likely require the interface for setting up the rules to change. Though, I see it being of great interest, and I would appreciate to get as much feedback as possible so that the feature is implemented in a way that meets as many people's needs as possible.

**Comment by FMCorz** [comment]
Grade-based rewards are available available with our add-on [Level up! Plus](https://levelup.plus). More information on the feature is available here: https://levelup.plus/docs/article/grade-based-rewards
